<a href="https://colab.research.google.com/github/Krishnapriya-TP/ML-projects/blob/main/naive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.impute import SimpleImputer
df=pd.read_csv("/content/owid-covid-data.csv")

ParserError: ignored

In [ ]:
print(df.shape)

(227186, 64)

In [ ]:
print(df.head)

<bound method NDFrame.head of        iso_code      continent     location        date  total_cases  \
0           AFG           Asia  Afghanistan  2020-02-24          5.0
1           AFG           Asia  Afghanistan  2020-02-25          5.0
2           AFG           Asia  Afghanistan  2020-02-26          5.0
3           AFG           Asia  Afghanistan  2020-02-27          5.0
4           AFG           Asia  Afghanistan  2020-02-28          5.0
...         ...            ...          ...         ...          ...
227181      URY  South America      Uruguay  2020-09-25       1967.0
227182      URY  South America      Uruguay  2020-09-26       1998.0
227183      URY  South America      Uruguay  2020-09-27       2008.0
227184      URY  South America      Uruguay  2020-09-28       2010.0
227185      URY  South America      Uruguay  2020-09-29       2033.0

        new_cases  new_cases_smoothed  total_deaths  new_deaths  \
0             5.0                 NaN           NaN         NaN
1             0.0                 NaN           NaN         NaN
2             0.0                 NaN           NaN         NaN
3             0.0                 NaN           NaN         NaN
4             0.0                 NaN           NaN         NaN
...           ...                 ...           ...         ...
227181        8.0              11.000          47.0         0.0
227182       31.0              13.429          47.0         0.0
227183       10.0              13.000          47.0         0.0
227184        2.0              11.857          47.0         0.0
227185       23.0              14.143          48.0         1.0

        new_cases_smoothed_per_million  ...  male_smokers  \
0                                  NaN  ...           NaN
1                                  NaN  ...           NaN
2                                  NaN  ...           NaN
3                                  NaN  ...           NaN
4                                  NaN  ...           NaN
...                                ...  ...           ...
227181                           3.214  ...          19.9
227182                           3.923  ...          19.9
227183                           3.798  ...          19.9
227184                           3.464  ...          19.9
227185                           4.132  ...           NaN

        handwashing_facilities  hospital_beds_per_thousand  life_expectancy  \
0                       37.746                         0.5            64.83
1                       37.746                         0.5            64.83
2                       37.746                         0.5            64.83
3                       37.746                         0.5            64.83
4                       37.746                         0.5            64.83
...                        ...                         ...              ...
227181                     NaN                         2.8            77.91
227182                     NaN                         2.8            77.91
227183                     NaN                         2.8            77.91
227184                     NaN                         2.8            77.91
227185                     NaN                         NaN              NaN

        human_development_index  population  \
0                         0.511  41128772.0
1                         0.511  41128772.0
2                         0.511  41128772.0
3                         0.511  41128772.0
4                         0.511  41128772.0
...                         ...         ...
227181                    0.817   3422796.0
227182                    0.817   3422796.0
227183                    0.817   3422796.0
227184                    0.817   3422796.0
227185                      NaN         NaN

        excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                        NaN                          NaN
1                                        NaN                          NaN
2                                        NaN                          NaN
3                                        NaN                          NaN
4                                        NaN                          NaN
...                                      ...                          ...
227181                                   NaN                          NaN
227182                                   NaN                          NaN
227183                                   NaN                          NaN
227184                                   NaN                          NaN
227185                                   NaN                          NaN

        excess_mortality  excess_mortality_cumulative_per_million
0                    NaN                                      NaN
1                    NaN                                      NaN
2                    NaN                                      NaN
3                    NaN                                      NaN
4                    NaN                                      NaN
...                  ...                                      ...
227181               NaN                                      NaN
227182               NaN                                      NaN
227183               NaN                                      NaN
227184               NaN                                      NaN
227185               NaN                                      NaN

[227186 rows x 64 columns]>

In [ ]:
print(df.tail)

<bound method NDFrame.tail of        iso_code      continent     location        date  total_cases  \
0           AFG           Asia  Afghanistan  2020-02-24          5.0
1           AFG           Asia  Afghanistan  2020-02-25          5.0
2           AFG           Asia  Afghanistan  2020-02-26          5.0
3           AFG           Asia  Afghanistan  2020-02-27          5.0
4           AFG           Asia  Afghanistan  2020-02-28          5.0
...         ...            ...          ...         ...          ...
227181      URY  South America      Uruguay  2020-09-25       1967.0
227182      URY  South America      Uruguay  2020-09-26       1998.0
227183      URY  South America      Uruguay  2020-09-27       2008.0
227184      URY  South America      Uruguay  2020-09-28       2010.0
227185      URY  South America      Uruguay  2020-09-29       2033.0

        new_cases  new_cases_smoothed  total_deaths  new_deaths  \
0             5.0                 NaN           NaN         NaN
1             0.0                 NaN           NaN         NaN
2             0.0                 NaN           NaN         NaN
3             0.0                 NaN           NaN         NaN
4             0.0                 NaN           NaN         NaN
...           ...                 ...           ...         ...
227181        8.0              11.000          47.0         0.0
227182       31.0              13.429          47.0         0.0
227183       10.0              13.000          47.0         0.0
227184        2.0              11.857          47.0         0.0
227185       23.0              14.143          48.0         1.0

        new_cases_smoothed_per_million  ...  male_smokers  \
0                                  NaN  ...           NaN
1                                  NaN  ...           NaN
2                                  NaN  ...           NaN
3                                  NaN  ...           NaN
4                                  NaN  ...           NaN
...                                ...  ...           ...
227181                           3.214  ...          19.9
227182                           3.923  ...          19.9
227183                           3.798  ...          19.9
227184                           3.464  ...          19.9
227185                           4.132  ...           NaN

        handwashing_facilities  hospital_beds_per_thousand  life_expectancy  \
0                       37.746                         0.5            64.83
1                       37.746                         0.5            64.83
2                       37.746                         0.5            64.83
3                       37.746                         0.5            64.83
4                       37.746                         0.5            64.83
...                        ...                         ...              ...
227181                     NaN                         2.8            77.91
227182                     NaN                         2.8            77.91
227183                     NaN                         2.8            77.91
227184                     NaN                         2.8            77.91
227185                     NaN                         NaN              NaN

        human_development_index  population  \
0                         0.511  41128772.0
1                         0.511  41128772.0
2                         0.511  41128772.0
3                         0.511  41128772.0
4                         0.511  41128772.0
...                         ...         ...
227181                    0.817   3422796.0
227182                    0.817   3422796.0
227183                    0.817   3422796.0
227184                    0.817   3422796.0
227185                      NaN         NaN

        excess_mortality_cumulative_absolute  excess_mortality_cumulative  \
0                                        NaN                          NaN
1                                        NaN                          NaN
2                                        NaN                          NaN
3                                        NaN                          NaN
4                                        NaN                          NaN
...                                      ...                          ...
227181                                   NaN                          NaN
227182                                   NaN                          NaN
227183                                   NaN                          NaN
227184                                   NaN                          NaN
227185                                   NaN                          NaN

        excess_mortality  excess_mortality_cumulative_per_million
0                    NaN                                      NaN
1                    NaN                                      NaN
2                    NaN                                      NaN
3                    NaN                                      NaN
4                    NaN                                      NaN
...                  ...                                      ...
227181               NaN                                      NaN
227182               NaN                                      NaN
227183               NaN                                      NaN
227184               NaN                                      NaN
227185               NaN                                      NaN

[227186 rows x 64 columns]>

In [ ]:
print(df.columns)

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_cases_smoothed_per_million', 'total_deaths_per_million',
       'new_deaths_per_million', 'new_deaths_smoothed_per_million',
       'reproduction_rate', 'icu_patients', 'icu_patients_per_million',
       'hosp_patients', 'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'total_tests', 'new_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
       'new_vaccinations', 'new_vaccinations_smoothed',
       'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
       'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
       'new_vaccinations_smoothed_per_million',
       'new_people_vaccinated_smoothed',
       'new_people_vaccinated_smoothed_per_hundred', 'stringency_index',
       'population_density', 'median_age', 'aged_65_older', 'aged_70_older',
       'gdp_per_capita', 'extreme_poverty', 'cardiovasc_death_rate',
       'diabetes_prevalence', 'female_smokers', 'male_smokers',
       'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index', 'population',
       'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
       'excess_mortality', 'excess_mortality_cumulative_per_million'],
      dtype='object')

In [ ]:
df.describe()

,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_cases_smoothed_per_million,total_deaths_per_million,new_deaths_per_million,new_deaths_smoothed_per_million,reproduction_rate,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
count,2.147030e+05,2.143940e+05,2.132490e+05,1.969290e+05,196840.000000,212228.000000,195916.000000,195827.000000,194693.000000,169418.000000,...,135930.000000,88804.000000,163199.000000,208788.000000,178889.000000,2.261590e+05,7.937000e+03,7937.000000,7988.000000,7937.000000
mean,3.747031e+06,9.725972e+03,9.752038e+03,6.010359e+04,106.120240,191.424086,726.842719,1.393979,1.388883,0.924962,...,32.923906,51.181815,3.132685,73.727577,0.727927,1.103652e+08,4.948458e+04,10.031814,14.249722,1390.272219
std,1.999632e+07,6.204685e+04,6.018804e+04,2.503751e+05,494.786127,677.142435,1004.337803,5.714169,3.327354,0.394647,...,13.783456,32.305821,2.593715,7.513695,0.150836,4.692235e+08,1.360795e+05,13.449434,26.164057,1764.574351
min,1.000000e+00,0.000000e+00,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,-0.060000,...,7.700000,1.188000,0.100000,53.280000,0.394000,4.700000e+01,-3.772610e+04,-28.450000,-95.920000,-1984.281517
25%,5.090000e+03,0.000000e+00,5.857000e+00,1.160000e+02,0.000000,1.337000,31.820000,0.000000,0.000000,0.730000,...,21.400000,19.351000,1.300000,69.500000,0.606000,8.367830e+05,4.510000e+01,0.660000,0.030000,33.529219
50%,5.485600e+04,4.900000e+01,9.085700e+01,1.195000e+03,1.000000,19.823000,232.560000,0.017000,0.197000,0.960000,...,33.100000,50.540000,2.500000,75.090000,0.750000,6.812344e+06,6.268500e+03,7.580000,7.400000,839.745148
75%,5.806090e+05,9.360000e+02,1.120714e+03,1.061200e+04,13.000000,139.268500,1087.032000,0.946000,1.324000,1.150000,...,41.500000,83.241000,4.280000,79.380000,0.851000,3.347587e+07,3.599970e+04,15.660000,19.492500,2205.531253
max,4.023756e+08,2.851878e+06,2.347186e+06,2.739589e+06,10798.000000,36421.827000,6383.925000,1185.420000,169.346000,5.680000,...,78.100000,100.000000,13.800000,86.750000,0.957000,4.721383e+09,1.240683e+06,76.550000,376.580000,10032.844512

In [ ]:
df.drop(['new_cases_smoothed'],axis=1,inplace=True)
df

,iso_code,continent,location,date,total_cases,new_cases,total_deaths,new_deaths,new_cases_smoothed_per_million,total_deaths_per_million,...,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,population,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,37.746,0.5,64.83,0.511,41128772.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227181,URY,South America,Uruguay,2020-09-25,1967.0,8.0,47.0,0.0,3.214,13.731,...,19.9,NaN,2.8,77.91,0.817,3422796.0,NaN,NaN,NaN,NaN
227182,URY,South America,Uruguay,2020-09-26,1998.0,31.0,47.0,0.0,3.923,13.731,...,19.9,NaN,2.8,77.91,0.817,3422796.0,NaN,NaN,NaN,NaN
227183,URY,South America,Uruguay,2020-09-27,2008.0,10.0,47.0,0.0,3.798,13.731,...,19.9,NaN,2.8,77.91,0.817,3422796.0,NaN,NaN,NaN,NaN
227184,URY,South America,Uruguay,2020-09-28,2010.0,2.0,47.0,0.0,3.464,13.731,...,19.9,NaN,2.8,77.91,0.817,3422796.0,NaN,NaN,NaN,NaN
227185,URY,South America,Uruguay,2020-09-29,2033.0,23.0,48.0,1.0,4.132,14.024,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.drop(['new_deaths_smoothed','new_cases_per_million','total_cases_per_million'],axis=1,inplace=True)
df

KeyError: ignored